# Generated by Django 5.1.4 on 2025-03-10 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creator_name', models.CharField(max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('legionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.legionary')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not relevant', 'Not relevant'), ('false', 'False'), ('incorrect', 'Incorrect'), ('inappropriate', 'Inappropriate'), ('sexually explicit', 'Sexually explicit'), ('other', 'Other')], max_length=100)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='social.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('legionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.legionary')),
            ],
        ),
        migrations.CreateModel(
            name='CommentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not relevant', 'Not relevant'), ('false', 'False'), ('incorrect', 'Incorrect'), ('inappropriate', 'Inappropriate'), ('sexually explicit', 'Sexually explicit'), ('other', 'Other')], max_length=100)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='social.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/posts/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creator_name', models.CharField(max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('legionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.legionary')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.post'),
        ),
        migrations.CreateModel(
            name='PostFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not relevant', 'Not relevant'), ('false', 'False'), ('incorrect', 'Incorrect'), ('inappropriate', 'Inappropriate'), ('sexually explicit', 'Sexually explicit'), ('other', 'Other')], max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='social.post')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('legionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='accounts.legionary')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerRequestFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not relevant', 'Not relevant'), ('false', 'False'), ('incorrect', 'Incorrect'), ('inappropriate', 'Inappropriate'), ('sexually explicit', 'Sexually explicit'), ('other', 'Other')], max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='social.prayerrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('legionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.legionary')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='social.question'),
        ),
        migrations.CreateModel(
            name='QuestionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not relevant', 'Not relevant'), ('false', 'False'), ('incorrect', 'Incorrect'), ('inappropriate', 'Inappropriate'), ('sexually explicit', 'Sexually explicit'), ('other', 'Other')], max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='social.question')),
            ],
        ),
    ]
