# Generated by Django 5.1.4 on 2025-01-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_downvotes_alter_post_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='content',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
